#!/bin/sh -xe
# This script hardcodes the `git describe` version as the program's version number.
# This is done to allow shellcheck --version to differ from the cabal version when
# building git snapshots.

file="app/Main.hs"
test -e "$file"
tmp=$(mktemp)
# Copied from shellcheck, but adapted for the case that git describe returns nothing (yet)
version=$(git describe 2>/dev/null || git rev-parse --short HEAD)
sed -e "s/=.*VERSIONSTRING.*/= \"$version\" -- VERSIONSTRING, DO NOT SUBMIT/" "$file" > "$tmp"
mv "$tmp" "$file"
