name: Build openreads-to-storygraph

on: push

jobs:
  build_source:
    name: Build
    needs: package_source
    strategy:
      matrix:
        build: [linux.x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Build source
        run: |
          mkdir -p bin
          mkdir -p bin/${{matrix.build}}
          ( cd bin && ../build/run_builder ../source/source.tar.gz ../build/${{matrix.build}} )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.build}}.bin
          path: bin/
